use crate::cxx::ffi::{
    ArkoorPaymentResult, BarkVtxo, Bolt11PaymentResult, LnurlPaymentResult, OffchainBalance,
    OnChainBalance, OnchainPaymentResult, PaymentTypes,
};
use crate::{parse_send_destination, utils, SendDestination, TOKIO_RUNTIME};
use anyhow::{bail, Context, Ok};
use bark::ark::bitcoin::hex::DisplayHex;
use bark::ark::bitcoin::{address, Address};
use logger::log::{self, info};
use std::path::Path;
use std::str::FromStr;

#[cxx::bridge(namespace = "bark_cxx")]
pub(crate) mod ffi {
    pub struct BarkVtxo {
        amount: u64,
        expiry_height: u32,
        exit_delta: u16,
        anchor_point: String,
    }

    pub enum PaymentTypes {
        Bolt11,
        Lnurl,
        Arkoor,
        Onchain,
    }

    pub struct Bolt11PaymentResult {
        bolt11_invoice: String,
        preimage: String,
        payment_type: PaymentTypes,
    }

    pub struct LnurlPaymentResult {
        lnurl: String,
        bolt11_invoice: String,
        preimage: String,
        payment_type: PaymentTypes,
    }

    pub struct ArkoorPaymentResult {
        amount_sat: u64,
        destination_pubkey: String,
        payment_type: PaymentTypes,
        vtxos: Vec<BarkVtxo>,
    }

    pub struct OnchainPaymentResult {
        txid: String,
        amount_sat: u64,
        destination_address: String,
        payment_type: PaymentTypes,
    }

    pub struct CxxArkInfo {
        network: String,
        asp_pubkey: String,
        round_interval_secs: u64,
        vtxo_exit_delta: u16,
        vtxo_expiry_delta: u16,
        htlc_expiry_delta: u16,
        max_vtxo_amount_sat: u64,
    }

    pub struct ConfigOpts {
        asp: String,
        esplora: String,
        bitcoind: String,
        bitcoind_cookie: String,
        bitcoind_user: String,
        bitcoind_pass: String,
        vtxo_refresh_expiry_threshold: u32,
        fallback_fee_rate: u64,
    }

    pub struct CreateOpts {
        regtest: bool,
        signet: bool,
        bitcoin: bool,
        mnemonic: String,
        birthday_height: *const u32,
        config: ConfigOpts,
    }

    pub struct SendManyOutput {
        destination: String,
        amount_sat: u64,
    }

    pub enum RefreshModeType {
        DefaultThreshold,
        ThresholdBlocks,
        ThresholdHours,
        Counterparty,
        All,
        Specific,
    }

    pub struct OffchainBalance {
        /// Coins that are spendable in the Ark, either in-round or out-of-round.
        pub spendable: u64,
        /// Coins that are in the process of being sent over Lightning.
        pub pending_lightning_send: u64,
        /// Coins that are in the process of unilaterally exiting the Ark.
        pub pending_exit: u64,
    }

    pub struct OnChainBalance {
        /// All coinbase outputs not yet matured
        pub immature: u64,
        /// Unconfirmed UTXOs generated by a wallet tx
        pub trusted_pending: u64,
        /// Unconfirmed UTXOs received from an external wallet
        pub untrusted_pending: u64,
        /// Confirmed and immediately spendable balance
        pub confirmed: u64,
    }

    extern "Rust" {
        fn init_logger();
        fn create_mnemonic() -> Result<String>;
        fn is_wallet_loaded() -> bool;
        fn close_wallet() -> Result<()>;
        fn persist_config(opts: ConfigOpts) -> Result<()>;
        fn get_ark_info() -> Result<CxxArkInfo>;
        fn get_onchain_address() -> Result<String>;
        fn offchain_balance() -> Result<OffchainBalance>;
        fn onchain_balance() -> Result<OnChainBalance>;
        fn get_onchain_utxos(no_sync: bool) -> Result<String>;
        unsafe fn get_vtxo_pubkey(index: *const u32) -> Result<String>;
        fn get_vtxos(no_sync: bool) -> Result<String>;
        fn bolt11_invoice(amount_msat: u64) -> Result<String>;
        fn claim_bolt11_payment(bolt11: &str) -> Result<()>;
        fn maintenance() -> Result<()>;
        fn sync() -> Result<()>;
        fn sync_ark() -> Result<()>;
        fn sync_rounds() -> Result<()>;
        fn load_wallet(datadir: &str, opts: CreateOpts) -> Result<()>;
        fn send_onchain(destination: &str, amount_sat: u64) -> Result<OnchainPaymentResult>;
        fn drain_onchain(destination: &str, no_sync: bool) -> Result<String>;
        fn send_many_onchain(outputs: Vec<SendManyOutput>, no_sync: bool) -> Result<String>;
        fn board_amount(amount_sat: u64) -> Result<String>;
        fn board_all() -> Result<String>;
        fn send_arkoor_payment(destination: &str, amount_sat: u64) -> Result<ArkoorPaymentResult>;
        unsafe fn send_bolt11_payment(
            destination: &str,
            amount_sat: *const u64,
        ) -> Result<Bolt11PaymentResult>;
        fn send_lnaddr(addr: &str, amount_sat: u64, comment: &str) -> Result<LnurlPaymentResult>;
        fn send_round_onchain(destination: &str, amount_sat: u64, no_sync: bool) -> Result<String>;
        fn offboard_specific(vtxo_ids: Vec<String>, destination_address: &str) -> Result<String>;
        fn offboard_all(destination_address: &str) -> Result<String>;
        fn derive_store_next_keypair() -> Result<String>;
        fn peak_keypair(index: u32) -> Result<String>;
        fn finish_lightning_receive(bolt11: String) -> Result<()>;
        fn refresh_vtxos(vtxos_json: String) -> Result<String>;
        fn send_lightning_payment(bolt11: String, amount_sat: u64) -> Result<String>;
        fn sync_exits() -> Result<()>;
        fn list_unspent() -> Result<String>;
    }
}

pub(crate) fn init_logger() {
    crate::init_logger()
}

pub(crate) fn create_mnemonic() -> anyhow::Result<String> {
    crate::create_mnemonic()
}

pub(crate) fn is_wallet_loaded() -> bool {
    crate::TOKIO_RUNTIME.block_on(crate::is_wallet_loaded())
}

pub(crate) fn close_wallet() -> anyhow::Result<()> {
    crate::TOKIO_RUNTIME.block_on(crate::close_wallet())
}

pub(crate) fn get_onchain_address() -> anyhow::Result<String> {
    let address = crate::TOKIO_RUNTIME.block_on(crate::onchain::address())?;
    Ok(address.to_string())
}

pub(crate) fn persist_config(opts: ffi::ConfigOpts) -> anyhow::Result<()> {
    let config_opts = utils::ConfigOpts {
        asp: Some(opts.asp),
        esplora: Some(opts.esplora),
        bitcoind: Some(opts.bitcoind),
        bitcoind_cookie: Some(opts.bitcoind_cookie),
        bitcoind_user: Some(opts.bitcoind_user),
        bitcoind_pass: Some(opts.bitcoind_pass),
        vtxo_refresh_expiry_threshold: Some(opts.vtxo_refresh_expiry_threshold),
        fallback_fee_rate: Some(opts.fallback_fee_rate),
    };

    crate::TOKIO_RUNTIME.block_on(async {
        let mut wallet_guard = crate::GLOBAL_WALLET.lock().await;
        let (w, _) = wallet_guard
            .as_mut()
            .ok_or_else(|| anyhow::anyhow!("Wallet not loaded"))?;
        let mut current_config = w.config().clone();
        config_opts.merge_into(&mut current_config)?;
        crate::persist_config(current_config).await
    })
}

pub(crate) fn get_ark_info() -> anyhow::Result<ffi::CxxArkInfo> {
    let info = crate::TOKIO_RUNTIME.block_on(crate::get_ark_info())?;
    Ok(ffi::CxxArkInfo {
        network: info.network.to_string(),
        asp_pubkey: info.asp_pubkey.to_string(),
        round_interval_secs: info.round_interval.as_secs(),
        vtxo_exit_delta: info.vtxo_exit_delta,
        vtxo_expiry_delta: info.vtxo_expiry_delta,
        htlc_expiry_delta: info.htlc_expiry_delta,
        max_vtxo_amount_sat: info.max_vtxo_amount.map_or(0, |a| a.to_sat()),
    })
}

pub(crate) fn offchain_balance() -> anyhow::Result<ffi::OffchainBalance> {
    let balance = crate::TOKIO_RUNTIME.block_on(crate::balance())?;
    Ok(ffi::OffchainBalance {
        spendable: balance.spendable.to_sat(),
        pending_lightning_send: balance.pending_lightning_send.to_sat(),
        pending_exit: balance.pending_exit.to_sat(),
    })
}

pub(crate) fn onchain_balance() -> anyhow::Result<ffi::OnChainBalance> {
    let balance = crate::TOKIO_RUNTIME.block_on(crate::onchain::onchain_balance())?;
    Ok(ffi::OnChainBalance {
        immature: balance.immature.to_sat(),
        trusted_pending: balance.trusted_pending.to_sat(),
        untrusted_pending: balance.untrusted_pending.to_sat(),
        confirmed: balance.confirmed.to_sat(),
    })
}

pub(crate) fn get_onchain_utxos(no_sync: bool) -> anyhow::Result<String> {
    crate::TOKIO_RUNTIME.block_on(crate::get_onchain_utxos(no_sync))
}

pub(crate) fn get_vtxo_pubkey(index: *const u32) -> anyhow::Result<String> {
    let index_opt = unsafe { index.as_ref().map(|r| *r) };
    crate::TOKIO_RUNTIME.block_on(crate::get_vtxo_pubkey(index_opt))
}

pub(crate) fn get_vtxos(no_sync: bool) -> anyhow::Result<String> {
    crate::TOKIO_RUNTIME.block_on(crate::get_vtxos())
}

pub(crate) fn bolt11_invoice(amount_msat: u64) -> anyhow::Result<String> {
    crate::TOKIO_RUNTIME.block_on(crate::bolt11_invoice(amount_msat))
}

pub(crate) fn claim_bolt11_payment(bolt11: &str) -> anyhow::Result<()> {
    crate::TOKIO_RUNTIME.block_on(crate::claim_bolt11_payment(bolt11.to_string()))
}

pub(crate) fn maintenance() -> anyhow::Result<()> {
    crate::TOKIO_RUNTIME.block_on(crate::maintenance())
}

pub(crate) fn sync() -> anyhow::Result<()> {
    crate::TOKIO_RUNTIME.block_on(crate::sync())
}

pub(crate) fn sync_ark() -> anyhow::Result<()> {
    crate::TOKIO_RUNTIME.block_on(crate::sync_ark())
}

pub(crate) fn sync_rounds() -> anyhow::Result<()> {
    crate::TOKIO_RUNTIME.block_on(crate::sync_rounds())
}

pub(crate) fn load_wallet(datadir: &str, opts: ffi::CreateOpts) -> anyhow::Result<()> {
    let config_opts = utils::ConfigOpts {
        asp: Some(opts.config.asp),
        esplora: Some(opts.config.esplora),
        bitcoind: Some(opts.config.bitcoind),
        bitcoind_cookie: Some(opts.config.bitcoind_cookie),
        bitcoind_user: Some(opts.config.bitcoind_user),
        bitcoind_pass: Some(opts.config.bitcoind_pass),
        vtxo_refresh_expiry_threshold: Some(opts.config.vtxo_refresh_expiry_threshold),
        fallback_fee_rate: Some(opts.config.fallback_fee_rate),
    };

    log::info!(
        "Loading wallet with datadir: {}, regtest: {}, signet: {}, bitcoin: {}, birthday_height: {:?}",
        datadir,
        opts.regtest,
        opts.signet,
        opts.bitcoin,
        unsafe { opts.birthday_height.as_ref().map(|r| *r) }
    );

    let create_opts = utils::CreateOpts {
        regtest: opts.regtest,
        signet: opts.signet,
        bitcoin: opts.bitcoin,
        mnemonic: bip39::Mnemonic::from_str(&opts.mnemonic)?,
        birthday_height: unsafe { opts.birthday_height.as_ref().map(|r| *r) },
        config: config_opts,
    };

    log::info!("Creating wallet with options: {:?}", create_opts);

    crate::TOKIO_RUNTIME.block_on(crate::load_wallet(Path::new(datadir), create_opts))
}

pub(crate) fn send_onchain(
    destination: &str,
    amount_sat: u64,
) -> anyhow::Result<OnchainPaymentResult> {
    let amount = bark::ark::bitcoin::Amount::from_sat(amount_sat);

    let ark_info = crate::TOKIO_RUNTIME.block_on(crate::get_ark_info())?;

    // Validate optional address string
    let address_unchecked = Address::<address::NetworkUnchecked>::from_str(destination)
        .with_context(|| format!("invalid destination address format: '{}'", destination))?;

    // Now require the network to match the wallet's network
    let destination_address = address_unchecked
        .require_network(ark_info.network)
        .with_context(|| {
            format!(
                "address '{}' is not valid for configured network {}",
                destination, ark_info.network
            )
        })?;

    info!(
        "Sending {} to onchain address {}",
        amount, destination_address
    );

    let txid =
        crate::TOKIO_RUNTIME.block_on(crate::send_onchain(destination_address.clone(), amount))?;

    Ok(OnchainPaymentResult {
        txid: txid.to_string(),
        amount_sat,
        destination_address: destination_address.to_string(),
        payment_type: PaymentTypes::Onchain,
    })
}

pub(crate) fn drain_onchain(destination: &str, no_sync: bool) -> anyhow::Result<String> {
    let txid = crate::TOKIO_RUNTIME.block_on(crate::drain_onchain(destination, no_sync))?;
    Ok(txid.to_string())
}

pub(crate) fn send_many_onchain(
    outputs: Vec<ffi::SendManyOutput>,
    no_sync: bool,
) -> anyhow::Result<String> {
    let txid = crate::TOKIO_RUNTIME.block_on(async {
        let mut rust_outputs = Vec::new();
        let wallet_guard = crate::GLOBAL_WALLET.lock().await;
        let w = wallet_guard.as_ref().unwrap();
        let net = w.properties().unwrap().network;
        for output in outputs {
            let address = Address::from_str(&output.destination)
                .unwrap()
                .require_network(net)
                .unwrap();
            let amount = bark::ark::bitcoin::Amount::from_sat(output.amount_sat);
            rust_outputs.push((address, amount));
        }
        crate::send_many_onchain(rust_outputs, no_sync).await
    })?;
    Ok(txid.to_string())
}

pub(crate) fn board_amount(amount_sat: u64) -> anyhow::Result<String> {
    let amount = bark::ark::bitcoin::Amount::from_sat(amount_sat);
    crate::TOKIO_RUNTIME.block_on(crate::board_amount(amount))
}

pub(crate) fn board_all() -> anyhow::Result<String> {
    crate::TOKIO_RUNTIME.block_on(crate::board_all())
}

pub(crate) fn send_arkoor_payment(
    destination: &str,
    amount_sat: u64,
) -> anyhow::Result<ArkoorPaymentResult> {
    let amount = bark::ark::bitcoin::Amount::from_sat(amount_sat);
    let oor_result =
        crate::TOKIO_RUNTIME.block_on(crate::send_arkoor_payment(destination, amount))?;

    Ok(ArkoorPaymentResult {
        vtxos: oor_result
            .iter()
            .map(|n| BarkVtxo {
                amount: n.amount().to_sat(),
                anchor_point: format!(
                    "{}:{}",
                    n.chain_anchor().txid.to_string(),
                    n.chain_anchor().vout.to_string()
                ),
                exit_delta: n.exit_delta(),
                expiry_height: n.expiry_height(),
            })
            .collect(),
        destination_pubkey: destination.to_string(),
        amount_sat,
        payment_type: PaymentTypes::Arkoor,
    })
}

pub(crate) fn send_bolt11_payment(
    destination: &str,
    amount_sat: *const u64,
) -> anyhow::Result<Bolt11PaymentResult> {
    let amount_opt = match unsafe { amount_sat.as_ref().map(|r| *r) } {
        Some(amount) => Some(bark::ark::bitcoin::Amount::from_sat(amount)),
        None => None,
    };

    let parsed_destination = parse_send_destination(destination)?;

    // --- Logic per destination type ---
    let invoice = match parsed_destination {
        SendDestination::Bolt11(invoice) => invoice,
        _ => bail!("Invalid destination type for send_bolt11_payment"),
    };

    let preimage = crate::TOKIO_RUNTIME
        .block_on(crate::send_bolt11_payment(invoice, amount_opt))?
        .to_lower_hex_string();

    Ok(Bolt11PaymentResult {
        preimage,
        bolt11_invoice: destination.to_string(),
        payment_type: PaymentTypes::Bolt11,
    })
}

pub(crate) fn send_lnaddr(
    addr: &str,
    amount_sat: u64,
    comment: &str,
) -> anyhow::Result<LnurlPaymentResult> {
    let amount = bark::ark::bitcoin::Amount::from_sat(amount_sat);
    let comment_opt = if comment.is_empty() {
        None
    } else {
        Some(comment)
    };
    let send_lnaddr_result =
        crate::TOKIO_RUNTIME.block_on(crate::send_lnaddr(addr, amount, comment_opt))?;

    Ok(LnurlPaymentResult {
        preimage: send_lnaddr_result.1.to_lower_hex_string(),
        bolt11_invoice: send_lnaddr_result.0.to_string(),
        lnurl: addr.to_string(),
        payment_type: PaymentTypes::Lnurl,
    })
}

pub(crate) fn send_round_onchain(
    destination: &str,
    amount_sat: u64,
    no_sync: bool,
) -> anyhow::Result<String> {
    let amount = bark::ark::bitcoin::Amount::from_sat(amount_sat);
    crate::TOKIO_RUNTIME.block_on(crate::send_round_onchain(destination, amount, no_sync))
}

pub(crate) fn offboard_specific(
    vtxo_ids: Vec<String>,
    destination_address: &str,
) -> anyhow::Result<String> {
    let ids = vtxo_ids
        .into_iter()
        .map(|s| bark::ark::VtxoId::from_str(&s))
        .collect::<Result<Vec<_>, _>>()?;

    let ark_info = crate::TOKIO_RUNTIME.block_on(crate::get_ark_info())?;

    let destination_address_opt = Address::<address::NetworkUnchecked>::from_str(
        &destination_address,
    )
    .with_context(|| {
        format!(
            "Invalid destination address format: '{}'",
            destination_address
        )
    })?;
    let addr = destination_address_opt
        .require_network(ark_info.network)
        .with_context(|| {
            format!(
                "Address '{}' is not valid for configured network {:?}",
                destination_address, ark_info.network
            )
        })?;

    if ids.is_empty() {
        bail!("At least one VTXO ID must be provided for specific offboarding");
    }

    info!(
        "Attempting to offboard {} specific VTXOs to {:?}",
        ids.len(),
        addr
    );

    let offboard_specific_result =
        crate::TOKIO_RUNTIME.block_on(crate::offboard_specific(ids, addr))?;

    Ok(offboard_specific_result.round.to_string())
}

pub(crate) fn offboard_all(destination_address: &str) -> anyhow::Result<String> {
    let ark_info = crate::TOKIO_RUNTIME.block_on(crate::get_ark_info())?;

    let destination_address_opt = Address::<address::NetworkUnchecked>::from_str(
        &destination_address,
    )
    .with_context(|| {
        format!(
            "Invalid destination address format: '{}'",
            destination_address
        )
    })?;
    let addr = destination_address_opt
        .require_network(ark_info.network)
        .with_context(|| {
            format!(
                "Address '{}' is not valid for configured network {:?}",
                destination_address, ark_info.network
            )
        })?;

    info!("Attempting to offboard all VTXOs to {:?}", addr);

    let offboard_all_result = crate::TOKIO_RUNTIME.block_on(crate::offboard_all(addr))?;

    Ok(offboard_all_result.round.to_string())
}

pub(crate) fn derive_store_next_keypair() -> anyhow::Result<String> {
    let keypair = TOKIO_RUNTIME.block_on(crate::derive_store_next_keypair())?;
    Ok(format!("{}", keypair.display_secret()))
}

pub(crate) fn peak_keypair(index: u32) -> anyhow::Result<String> {
    let keypair = TOKIO_RUNTIME.block_on(crate::peak_keypair(index))?;
    Ok(format!("{}", keypair.display_secret()))
}

pub(crate) fn finish_lightning_receive(bolt11: String) -> anyhow::Result<()> {
    let invoice = bolt11.parse()?;
    TOKIO_RUNTIME.block_on(crate::finish_lightning_receive(invoice))
}

pub(crate) fn refresh_vtxos(vtxos_json: String) -> anyhow::Result<String> {
    let vtxos: Vec<bark::ark::Vtxo> = serde_json::from_str(&vtxos_json)?;
    let result = TOKIO_RUNTIME.block_on(crate::refresh_vtxos(vtxos))?;
    serde_json::to_string(&result).map_err(Into::into)
}

pub(crate) fn send_lightning_payment(bolt11: String, amount_sat: u64) -> anyhow::Result<String> {
    let invoice = bolt11.parse()?;
    let amount = if amount_sat > 0 {
        Some(bark::ark::bitcoin::Amount::from_sat(amount_sat))
    } else {
        None
    };
    let preimage = TOKIO_RUNTIME.block_on(crate::send_lightning_payment(invoice, amount))?;
    Ok(preimage.to_lower_hex_string())
}

pub(crate) fn sync_exits() -> anyhow::Result<()> {
    TOKIO_RUNTIME.block_on(crate::sync_exits())
}

pub(crate) fn list_unspent() -> anyhow::Result<String> {
    let unspent = TOKIO_RUNTIME.block_on(crate::onchain::list_unspent())?;
    serde_json::to_string(&unspent).map_err(Into::into)
}
