name: CI
on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_checks_and_tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Install Nix
      #   uses: DeterminateSystems/nix-installer-action@main
      
      # - name: Enable Nix Magic Cache
      #   uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check formatting (bark-cpp)
        run: nix develop .# --command bash -c "unset SDKROOT && cd bark-cpp && cargo fmt -- --check"
      
      - name: Run tests (bark-cpp)
        run: nix develop .# --command bash -c "unset SDKROOT && cd bark-cpp && cargo test"

  android_build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Install Nix
      #   uses: DeterminateSystems/nix-installer-action@main
      
      # - name: Enable Nix Magic Cache
      #   uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Build bark-cpp for Android
        run: nix develop .# --command bash -c "unset SDKROOT && cd bark-cpp && ./build-android.sh"
      
      - name: Install example app dependencies
        run: nix develop .# --command bash -c "cd react-native-nitro-ark && yarn install"
      
      - name: Build example Android app
        run: nix develop .# --command bash -c "cd react-native-nitro-ark && yarn example build:android"

  # ios_build:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@main
      
  #     - name: Enable Nix Magic Cache
  #       uses: DeterminateSystems/magic-nix-cache-action@main
      
  #     - name: Build bark-cpp for iOS
  #       run: nix develop .# --command bash -c "cd bark-cpp && ./build-ios.sh"
      
  #     - name: Install example app dependencies
  #       run: nix develop .# --command bash -c "cd react-native-nitro-ark && yarn install"
      
  #     - name: Build example iOS app
  #       run: nix develop .# --command bash -c "cd react-native-nitro-ark && yarn example build:ios"